version: '3'
services:
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile 
    container_name: backend-container
    ports:
      - "4000:3000" 
    networks:
      - my-network  

  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile  
    container_name: frontend-container
    ports:
      - "3000:80"  
    networks:
      - my-network 

networks:
  my-network:
    driver: bridge
